### ISSUE TITLE
「启航计划」一、二、三等奖答辩安排

### ISSUE THREAD

**Issue by sunzhongkai588** [PFCCLab/Starter#100]
> [!NOTE]
> 一、二、三等奖，需要营员**主动申请**并完成答辩，所有学员均可申请。

### 参与方式

1. 在 1.22（周一） 23:59 之前，在该 Issue 区下回复 `申请答辩`，即申请成功。
2. 在 1.23（周二） 23:59 之前，把答辩 PPT 发送到 <ext_paddle_oss@baidu.com>。
3. 在 1.24（周三）～ 1.25（周四） ，按照安排参与答辩。

> PPT 模板 ➡️ [启航计划答辩模板](https://github.com/PFCCLab/Starter/blob/main/Reports/启航计划答辩模板.pptx)

### 答辩时间

- 每人 10 分钟陈述 + 5 分钟 QA。

### 答辩评委

- 固定 [@sunzhongkai](https://github.com/sunzhongkai) + 助教（[@ooooo-create](https://github.com/ooooo-create)/[@chenjjcccc](https://github.com/chenjjcccc)）
- 涉及到 MIX 任务 [@ligoml](https://github.com/ligoml)/[@LokeZhou](https://github.com/LokeZhou) 参加，涉及到基础方向任务 [@luotao1](https://github.com/luotao1)/[@jzhang533](https://github.com/jzhang533) 参加。

### 答辩流程

1. 使用如流答辩，1.17 之前把 PPT 到邮箱 <ext_paddle_oss@baidu.com>。
2. 每场会议后统一讨论答辩情况和打分。
3. 答辩同学不能旁听其他同学答辩内容，请提前如流在线，会 call 各位学员。
4. 最终一、二、三等奖名单会公布在群里和 Issue 区。

### 评分标准：

**总分** = **代码及 PR 贡献度** \* 50% + **开源协作贡献度** \* 30% + **个人沉淀** \* 20%

- 代码及 PR 贡献度：快乐开源 PR 贡献量、任务难度...（占总分的 50%）
- 开源协作贡献度：主动开展新任务、积极解决别人问题...（占总分的 30%）
- 个人沉淀：沉淀技术思考、提出可行性建议、周报质量...（占总分的 20%）

### 奖品

- 一等奖：PS5 🎮
- 二等奖：Apple Watch SE ⌚️
- 三等奖：Airpods（第三代）🎧

**Comment by Tsaiyue** [comment]
申请答辩

**Comment by zbt78** [comment]
申请答辩

**Comment by ooooo-create** [comment]
申请答辩
