### ISSUE TITLE
「启航计划」第二期答辩安排

### ISSUE THREAD

**Issue by Harryoung** [PFCCLab/Starter#219]
> [!NOTE]
> 一、二、三等奖，需要营员**主动申请**并完成答辩，所有学员均可申请。

### 参与方式

1. 在 5.24（周五） 23:59 之前，在该 Issue 区下回复 `申请答辩`，即申请成功。
2. 在 5.24（周五） 23:59 之前，把答辩 PPT 发送到 <ext_paddle_oss@baidu.com>，主题为「启航计划第二期答辩申请」。
3. 在 5.27（周一）～ 5.28（周二） ，按照安排参与答辩。

> PPT 模板 ➡️ [启航计划答辩模板](https://github.com/PFCCLab/Starter/blob/main/Reports/启航计划答辩模板.pptx)

### 答辩时间

- 每人 10 分钟陈述 + 5 分钟 QA。

### 答辩评委

- 固定评委：[@Harryoung ](https://github.com/Harryoung)、助教[@cmcamdy ](https://github.com/cmcamdy)
- 各专项团分别邀请对应的导师作为评委，探索团邀请[@luotao1 ](https://github.com/luotao1)作为评委。

### 答辩流程

1. 使用如流答辩。
2. 每场会议后统一讨论答辩情况和打分。
3. 答辩同学不能旁听其他同学答辩内容，请提前如流在线，会 call 各位学员。
4. 最终一、二、三等奖名单会公布在群里和 Issue 区。

### 评分标准：

**总分** = **代码及 PR 贡献度** \* 50% + **开源协作贡献度** \* 30% + **个人沉淀** \* 20%

- 代码及 PR 贡献度：快乐开源 PR 贡献量、任务难度...（占总分的 50%）
- 开源协作贡献度：主动开展新任务、积极解决别人问题...（占总分的 30%）
- 个人沉淀：沉淀技术思考、提出可行性建议、周报质量...（占总分的 20%）

### 奖品

- 一等奖：PS5 🎮
- 二等奖：Apple Watch SE ⌚️
- 三等奖：Airpods（第三代）🎧

**Comment by InsaneOnion** [comment]
申请答辩

**Comment by Eddie-Wang1120** [comment]
申请答辩

**Comment by wufei2** [comment]
申请答辩

**Comment by Wang-ZengWei** [comment]
申请答辩

**Comment by Wang-ZengWei** [comment]
申请答辩
